### PR TITLE
Add plugins

### PR DESCRIPTION
**Pull request by OlivierMary**
Add plugins on Jenkins container.

### CODE REVIEW

**Comment by maxfields2000** [comment]
I'm considering this.  I don't mind have the plugins file be part of the Dockerfile push. However, what plugins get installed is not something I want to set by default.  Ant and maven-plugin are common plugins but not everyone uses them and users should be free to pick there own. Unfortunately the way the plugin bootstrap scripts work for the Cloudbees base image there's no way to "comment out" entries in plugins.txt.  

So "plugins.txt" would need to be empty to meet my requirements (let users decide what to install by default).  Which might be okay, though it won't be clear. So a comment is needed in the dockerfile on how to use the plugins.txt file with examples.

As a result if you change the PR I'll accept it with the following changes:
1. leave plugins.txt as an empty text file
2. In the docker file add a good comment for how plugins.txt can be used, you can include the three plugins you think are a good idea there.

**Comment by OlivierMary** [comment]
Sure, I had put random plugin in plugins.txt, for me here it's just an example of what we can do with a Dockerfile to run jenkins, a tutorial. So anyone can adapt for his usage.

I change my PR.

**Comment by OlivierMary** [comment]
Done.

**Comment by maxfields2000** [comment]
:+1: Exceelent. I should've pulled this in sooner. Love it.

**Pull request merged**
